const simpleGit = require('simple-git');
const fs = require('fs');
const path = require('path');
const dayjs = require('dayjs');
const axios = require('axios');

// === CONFIG ===
const CONFIG = {
  // Repos to scan for activity (add your repos here)
  repos: [
    { name: 'claude-controller', path: 'C:/Users/51 TALK/Downloads/Repos/claude controller' },
    { name: 'AIEC-agent-hub', path: 'C:/Users/51 TALK/Downloads/Repos/AIEC-agent-hub' },
    { name: 'feshiu-web', path: 'C:/Users/51 TALK/Downloads/Repos/feshiu-web' },
    { name: 'daily-standup-reporter', path: 'C:/Users/51 TALK/Downloads/Repos/daily-standup-reporter' },
  ],
  // Git author to filter commits by
  gitAuthor: 'Youssef',
  // Output directory for daily logs
  outputDir: path.join(__dirname, 'logs'),
  // How many days back to scan (default: today only)
  daysBack: 1,
  // WhatsApp bot endpoint (optional - send report to your phone)
  whatsappEndpoint: 'http://localhost:6566/send',
  whatsappChatId: '201220730174@s.whatsapp.net',
};

// === GATHER GIT ACTIVITY ===
async function getGitActivity(repoConfig, since, until) {
  const git = simpleGit(repoConfig.path);

  try {
    const log = await git.log([
      '--since=' + since,
      '--until=' + until,
      '--author=' + CONFIG.gitAuthor,
      '--all',
    ]);

    if (!log.all.length) return null;

    const commits = log.all.map(c => ({
      message: c.message,
      date: c.date,
      hash: c.hash.substring(0, 7),
    }));

    // Get files changed today
    const diffSummary = await git.diffSummary([`--since=${since}`, 'HEAD~' + Math.min(log.all.length, 20), 'HEAD']).catch(() => null);

    return {
      repo: repoConfig.name,
      commits,
      filesChanged: diffSummary ? diffSummary.files.length : commits.length,
    };
  } catch (err) {
    console.log(`  ⚠ Could not read ${repoConfig.name}: ${err.message}`);
    return null;
  }
}

// === GATHER ALL ACTIVITY ===
async function gatherActivity(date) {
  const targetDate = dayjs(date || undefined);
  const since = targetDate.startOf('day').format('YYYY-MM-DDTHH:mm:ss');
  const until = targetDate.add(1, 'day').startOf('day').format('YYYY-MM-DDTHH:mm:ss');
  const dateStr = targetDate.format('YYYY-MM-DD');

  console.log(`\n📊 Scanning activity for ${dateStr}...\n`);

  const activities = [];

  for (const repo of CONFIG.repos) {
    if (!fs.existsSync(repo.path)) {
      console.log(`  ⚠ Skipping ${repo.name} (path not found)`);
      continue;
    }
    console.log(`  🔍 Scanning ${repo.name}...`);
    const activity = await getGitActivity(repo, since, until);
    if (activity) {
      activities.push(activity);
      console.log(`     ✓ ${activity.commits.length} commits, ${activity.filesChanged} files changed`);
    } else {
      console.log(`     - No activity`);
    }
  }

  return { date: dateStr, activities };
}

// === GENERATE REPORT ===
function generateReport(data) {
  const { date, activities } = data;
  const totalCommits = activities.reduce((sum, a) => sum + a.commits.length, 0);
  const totalFiles = activities.reduce((sum, a) => sum + a.filesChanged, 0);

  let report = `# Daily Standup — ${date}\n\n`;

  if (totalCommits === 0) {
    report += `No git activity recorded today.\n`;
    return report;
  }

  report += `## Summary\n`;
  report += `- **${totalCommits}** commits across **${activities.length}** repos\n`;
  report += `- **${totalFiles}** files changed\n\n`;

  report += `## What I Did\n`;
  for (const activity of activities) {
    report += `\n### ${activity.repo}\n`;
    for (const commit of activity.commits) {
      // Clean up commit messages
      const msg = commit.message.split('\n')[0]; // first line only
      report += `- ${msg} (\`${commit.hash}\`)\n`;
    }
  }

  report += `\n## Active Repos\n`;
  for (const activity of activities) {
    report += `- ${activity.repo}: ${activity.commits.length} commits\n`;
  }

  report += `\n---\n*Generated by Daily Standup Reporter*\n`;

  return report;
}

// === SAVE LOG ===
function saveLog(date, report) {
  if (!fs.existsSync(CONFIG.outputDir)) {
    fs.mkdirSync(CONFIG.outputDir, { recursive: true });
  }

  const filename = `${date}.md`;
  const filepath = path.join(CONFIG.outputDir, filename);
  fs.writeFileSync(filepath, report, 'utf8');
  console.log(`\n✅ Log saved: ${filepath}`);
  return filepath;
}

// === SEND TO WHATSAPP (optional) ===
async function sendToWhatsApp(report) {
  try {
    await axios.post(CONFIG.whatsappEndpoint, {
      chatId: CONFIG.whatsappChatId,
      message: report,
    });
    console.log('📱 Sent to WhatsApp');
  } catch (err) {
    console.log('📱 WhatsApp not available (bot not running)');
  }
}

// === MAIN ===
async function main() {
  const args = process.argv.slice(2);
  const dateArg = args.find(a => /^\d{4}-\d{2}-\d{2}$/.test(a));
  const sendWA = args.includes('--whatsapp') || args.includes('-w');

  const data = await gatherActivity(dateArg);
  const report = generateReport(data);

  console.log('\n' + '='.repeat(60));
  console.log(report);
  console.log('='.repeat(60));

  const filepath = saveLog(data.date, report);

  if (sendWA) {
    await sendToWhatsApp(report);
  }

  return { report, filepath };
}

// Export for use by OpenClaw or other tools
module.exports = { main, gatherActivity, generateReport, saveLog, CONFIG };

// Run if called directly
if (require.main === module) {
  main().catch(console.error);
}
